apiVersion: v1
kind: Service
metadata:
  name: quotes
  namespace: quotes-ns # same as delpoyement & namespace yaml
spec:
  selector:
    app: quotes-app #same as deployment yaml
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

